from app.models.app_document import AppUploadedDocument
from app.models.entrega_catalog import ChoferEntrega, ClienteEntrega, LugarEntrega, ProductoTerminado
from app.models.domain import (
    AguaRegistro,
    BolsonRegistro,
    ColumnaIntercambio,
    ConsumoStock,
    Entrega,
    EntregaEvento,
    Equipo,
    IngresoStock,
    MaintenanceAttachment,
    MaintenanceComponent,
    MaintenanceFailure,
    MaintenanceOrder,
    MaintenanceOrderResource,
    MaintenancePlan,
    MaintenancePrediction,
    MaintenanceResource,
    Operador,
    ProductoCatalogo,
    ProductoColor,
    ReactorRegistro,
    SalmueraAnalisis8hs,
    SalmueraRegistro,
    StockAjuste,
)
from app.models.shift import ShiftHandover, ShiftHandoverWarningAction, ShiftSession
from app.models.lab_reagent import LaboratoryReagent, LaboratoryReagentUsage
from app.models.planificacion import PlanificacionActividad, PlanificacionDependencia
from app.models.security_audit import SecurityAuditLog
from app.models.deadline_alert_email import DeadlineAlertEmail
from app.models.plant_stop import PlantStopAlertEmail, PlantStopEvent
from app.models.deadline_reminder_sent import DeadlineReminderSent
from app.models.user import PermisoUsuario, User
from app.models.vencimiento import SectorVencimiento, Vencimiento, VencimientoHistorial
from app.models.sgi import (
    SgiDocumento,
    SgiDocumentoHistorial,
    SgiNotificacion,
    SgiProcedimientoAnexo,
    SgiProcedimientoAprobacion,
    SgiProcedimientoControlCambio,
    SgiProcedimientoRegistro,
    SgiProcedimientoRevision,
)

__all__ = [
    "AppUploadedDocument",
    "User",
    "PermisoUsuario",
    "Operador",
    "SalmueraRegistro",
    "SalmueraAnalisis8hs",
    "BolsonRegistro",
    "ReactorRegistro",
    "AguaRegistro",
    "ColumnaIntercambio",
    "ProductoCatalogo",
    "IngresoStock",
    "ConsumoStock",
    "StockAjuste",
    "Equipo",
    "MaintenanceComponent",
    "MaintenanceFailure",
    "MaintenanceAttachment",
    "MaintenancePlan",
    "MaintenanceOrder",
    "MaintenanceResource",
    "MaintenanceOrderResource",
    "MaintenancePrediction",
    "ProductoColor",
    "Entrega",
    "EntregaEvento",
    "ProductoTerminado",
    "ClienteEntrega",
    "LugarEntrega",
    "ChoferEntrega",
    "ShiftSession",
    "ShiftHandover",
    "ShiftHandoverWarningAction",
    "LaboratoryReagent",
    "LaboratoryReagentUsage",
    "PlanificacionActividad",
    "PlanificacionDependencia",
    "SecurityAuditLog",
    "DeadlineReminderSent",
    "DeadlineAlertEmail",
    "PlantStopAlertEmail",
    "PlantStopEvent",
    "SectorVencimiento",
    "Vencimiento",
    "VencimientoHistorial",
    "SgiDocumento",
    "SgiDocumentoHistorial",
    "SgiProcedimientoRevision",
    "SgiProcedimientoControlCambio",
    "SgiProcedimientoRegistro",
    "SgiProcedimientoAnexo",
    "SgiProcedimientoAprobacion",
    "SgiNotificacion",
]
