"""domain_tables

Revision ID: 283ddb2c1925
Revises: 20250329_0002
Create Date: 2026-03-29 04:57:29.233694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283ddb2c1925'
down_revision: Union[str, Sequence[str], None] = '20250329_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agua_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_iso', sa.String(length=16), nullable=False),
    sa.Column('hora_hm', sa.String(length=8), nullable=False),
    sa.Column('turno', sa.String(length=64), nullable=False),
    sa.Column('operador', sa.String(length=256), nullable=False),
    sa.Column('lote', sa.String(length=128), nullable=False),
    sa.Column('numero_columna', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('dureza', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agua_registros_fecha_iso'), 'agua_registros', ['fecha_iso'], unique=False)
    op.create_table('bolson_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_iso', sa.String(length=16), nullable=False),
    sa.Column('hora_hm', sa.String(length=8), nullable=False),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bolson_registros_fecha_iso'), 'bolson_registros', ['fecha_iso'], unique=False)
    op.create_table('columnas_intercambio_ionico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('columna_numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=64), nullable=False),
    sa.Column('fecha_regeneracion', sa.String(length=32), nullable=True),
    sa.Column('hora_regeneracion', sa.String(length=16), nullable=True),
    sa.Column('dureza_salida_ppm', sa.Float(), nullable=True),
    sa.Column('dureza_post_regeneracion_ppm', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.Column('updated_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_equipo', sa.String(length=256), nullable=False),
    sa.Column('descripcion', sa.String(length=512), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('producto', sa.String(length=256), nullable=False),
    sa.Column('marca', sa.String(length=256), nullable=False),
    sa.Column('vencimiento', sa.String(length=64), nullable=False),
    sa.Column('lote', sa.String(length=128), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=16), nullable=False),
    sa.Column('hora', sa.String(length=8), nullable=False),
    sa.Column('operador', sa.String(length=256), nullable=False),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operadores_nombre'), 'operadores', ['nombre'], unique=True)
    op.create_table('producto_colores',
    sa.Column('nombre_clave', sa.String(length=256), nullable=False),
    sa.Column('nombre_display', sa.String(length=256), nullable=False),
    sa.Column('color_hex', sa.String(length=16), nullable=False),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('nombre_clave')
    )
    op.create_table('productos_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('nombre_producto', sa.String(length=256), nullable=False),
    sa.Column('tipo_producto', sa.String(length=32), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria', 'nombre_producto', name='uq_catalogo_cat_nombre')
    )
    op.create_table('reactor_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_iso', sa.String(length=16), nullable=False),
    sa.Column('hora_hm', sa.String(length=8), nullable=False),
    sa.Column('operador', sa.String(length=256), nullable=False),
    sa.Column('lote', sa.String(length=128), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('densidad', sa.Float(), nullable=False),
    sa.Column('concentracion_tabla', sa.Float(), nullable=False),
    sa.Column('exceso_naoh', sa.Float(), nullable=False),
    sa.Column('exceso_na2co3', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactor_registros_fecha_iso'), 'reactor_registros', ['fecha_iso'], unique=False)
    op.create_table('salmuera_registros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_iso', sa.String(length=16), nullable=False),
    sa.Column('hora_hm', sa.String(length=8), nullable=False),
    sa.Column('electrolizador', sa.Integer(), nullable=False),
    sa.Column('cantidad_celdas', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=64), nullable=False),
    sa.Column('voltajes_json', sa.Text(), nullable=False),
    sa.Column('voltaje_total', sa.Float(), nullable=False),
    sa.Column('amperaje', sa.Float(), nullable=False),
    sa.Column('caudal_agua_l_h', sa.Float(), nullable=False),
    sa.Column('caudal_salmuera_l_h', sa.Float(), nullable=False),
    sa.Column('hipo_conc', sa.Float(), nullable=False),
    sa.Column('hipo_exceso_soda', sa.Float(), nullable=False),
    sa.Column('sal_temp', sa.Float(), nullable=False),
    sa.Column('sal_conc', sa.Float(), nullable=False),
    sa.Column('sal_ph', sa.Float(), nullable=False),
    sa.Column('soda_conc', sa.Float(), nullable=False),
    sa.Column('declor_ph', sa.Float(), nullable=False),
    sa.Column('operador', sa.String(length=256), nullable=False),
    sa.Column('lote', sa.String(length=128), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('atraso_motivo', sa.Text(), nullable=True),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salmuera_registros_fecha_iso'), 'salmuera_registros', ['fecha_iso'], unique=False)
    op.create_table('consumos_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('producto', sa.String(length=256), nullable=False),
    sa.Column('marca', sa.String(length=256), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=16), nullable=False),
    sa.Column('hora', sa.String(length=8), nullable=False),
    sa.Column('operador', sa.String(length=256), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('created_at_iso', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permiso', sa.String(length=64), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permiso', name='uq_permiso_user_perm')
    )
    op.create_index(op.f('ix_permisos_usuario_user_id'), 'permisos_usuario', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permisos_usuario_user_id'), table_name='permisos_usuario')
    op.drop_table('permisos_usuario')
    op.drop_table('consumos_stock')
    op.drop_index(op.f('ix_salmuera_registros_fecha_iso'), table_name='salmuera_registros')
    op.drop_table('salmuera_registros')
    op.drop_index(op.f('ix_reactor_registros_fecha_iso'), table_name='reactor_registros')
    op.drop_table('reactor_registros')
    op.drop_table('productos_catalogo')
    op.drop_table('producto_colores')
    op.drop_index(op.f('ix_operadores_nombre'), table_name='operadores')
    op.drop_table('operadores')
    op.drop_table('ingresos_stock')
    op.drop_table('equipos')
    op.drop_table('columnas_intercambio_ionico')
    op.drop_index(op.f('ix_bolson_registros_fecha_iso'), table_name='bolson_registros')
    op.drop_table('bolson_registros')
    op.drop_index(op.f('ix_agua_registros_fecha_iso'), table_name='agua_registros')
    op.drop_table('agua_registros')
    # ### end Alembic commands ###
